name: neurolearn_ai
description: "Learning Without Limits — One Story at a Time"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Core UI & Navigation
  cupertino_icons: ^1.0.6
  flutter_animate: ^4.2.0+1
  lottie: ^2.7.0
  flutter_svg: ^2.0.9
  
  # State Management
  provider: ^6.1.1
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9
  
  # Backend & API
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  http: ^1.1.0
  dio: ^5.4.0
  
  # Audio & Voice
  flutter_tts: ^3.8.5
  speech_to_text: ^6.6.0
  audioplayers: ^5.2.0
  record: ^5.0.4
  file_picker: ^6.1.1
  
  # AI & ML
  dart_openai: ^5.1.0
  google_ml_kit: ^0.16.3
  camera: ^0.10.5+9
  camera_web: ^0.3.2+4
  image: ^4.1.3
  
  # Local Storage
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Utilities
  path_provider: ^2.1.1
  permission_handler: ^11.1.0
  connectivity_plus: ^5.0.2
  uuid: ^4.2.1
  intl: ^0.19.0
  
  # Animations & Gestures
  rive: ^0.12.4
  flutter_staggered_animations: ^1.1.1
  
  # Accessibility
  flutter_accessibility_service: ^0.2.1
  
  # Charts for dashboard
  fl_chart: ^0.65.0
  
  # UI and Navigation
  go_router: ^7.1.1
  
  # Added for real web-based emotion detection using MorphCast SDK
  js: ^0.6.7
  flutter_js: ^0.8.0
  webview_flutter: ^4.4.2
  webview_flutter_web: ^0.2.2+4
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.7
  hive_generator: ^2.0.1
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/animations/
    - assets/sounds/
    - assets/stories/
    - assets/characters/
    - assets/icons/
    - assets/models/
    - assets/fonts/
  
  # fonts:
  #   - family: ComicNeue
  #     fonts:
  #       - asset: assets/fonts/ComicNeue-Regular.ttf
  #       - asset: assets/fonts/ComicNeue-Bold.ttf
  #         weight: 700
  #   - family: OpenDyslexic
  #     fonts:
  #       - asset: assets/fonts/OpenDyslexic-Regular.otf
  #       - asset: assets/fonts/OpenDyslexic-Bold.otf
  #         weight: 700 